spring:
  #thymeleaf的配置
  thymeleaf:
    mode: HTML
  #配置数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  #spring data jpa 映射表结构配置
  jpa:
    hibernate:
      ddl-auto: update
    #把sql语句输出在控制台显示
    show-sql: true
    #配置messages全局路径

    #日志级别
logging:
  level:
    root: info
    com.zcs: debug
  #指定日志文件放的位置
  file: log/blog.log

  #属性路径
comment.avatar: /images/OO.jpg
